sudo: required
services:
  - docker

before_install:
  - docker build -t myimage -f Dockerfile.dev .

script:
  - docker run myimage npm run test -- --coverage

# deploy:
#   provider: elasticbeanstalk
#   region: "us-east-2"
#   app: "docker-react"
#   env: "Dockerreact-env"
#   bucket_name: "elasticbeanstalk-us-east-2-414387038831"
#   bucket_path: "docker-react"
#   on:
#     branch: master
